#!/bin/bash
DIR="$(cd "$(dirname "$0")/../../" && pwd)"
source "$DIR/config.sh"

# Get Todays Date. YYYY-MM-DD
current_date=$(date +"%Y-%m-%d")


# Define target date and command below. 
# commands YR-MON-Day["TARGET-DATE-YOU-WANT"]="THE COMMAND YOU WANT TO RUN"


declare -A commands
commands["2023-12-07"]="/home/alienatedmammal/Documents/RustBackups/wipescripts/./Fullwipe.sh && sed -i 's/1113833374/4244780/g' /home/alienatedmammal/lgsm/config-lgsm/rustserver/common.cfg ; sed -i 's/1113833374/4244780/g' /home/alienatedmammal/lgsm/config-lgsm/rustserver/rustserver.cfg ; sed -i 's/12\/7\/23/12\/21\/23/g' /home/alienatedmammal/lgsm/config-lgsm/rustserver/common.cfg ; sed -i 's/12\/7\/23/12\/21\/23/g' /home/alienatedmammal/lgsm/config-lgsm/rustserver/rustserver.cfg ; sed -i 's/12\/7\/23/12\/21\/23/g' /home/alienatedmammal/serverfiles/oxide/config/ServerInfo.json ; sed -i 's/12\/7\/23/12\/21\/23/g' /home/alienatedmammal/serverfiles/oxide/config/SmartChatBot.json ; echo Files have been copied >> /home/alienatedmammal/Documents/RustBackups/wipescripts/Logs/Logs.txt || echo Failed to copy files >> /home/alienatedmammal/Documents/RustBackups/wipescripts/Logs/Logs.txt && /home/alienatedmammal/Documents/RustBackups/wipescripts/./ServerStart.sh"
commands["2023-12-21"]="/home/alienatedmammal/Documents/RustBackups/wipescripts/./Mapwipe.sh && sed -i 's/12\/21\/23/1\/4\/24/g' /home/alienatedmammal/lgsm/config-lgsm/rustserver/common.cfg ; sed -i 's/12\/21\/23/1\/4\/24/g' /home/alienatedmammal/lgsm/config-lgsm/rustserver/rustserver.cfg ; sed -i 's/12\/21\/23/1\/4\/24/g' /home/alienatedmammal/serverfiles/oxide/config/ServerInfo.json ; sed -i 's/12\/21\/23/1\/4\/24/g' /home/alienatedmammal/serverfiles/oxide/config/SmartChatBot.json ; echo Files have been copied >> /home/alienatedmammal/Documents/RustBackups/wipescripts/Logs/Logs.txt || echo Failed to copy files >> /home/alienatedmammal/Documents/RustBackups/wipescripts/Logs/Logs.txt &&  echo Server is now starting.... >> /home/alienatedmammal/Documents/RustBackups/wipescripts/Logs/Logs.txt ; /home/alienatedmammal/Documents/RustBackups/wipescripts/./ServerStart.sh"
commands["2024-01-04"]="/home/alienatedmammal/Documents/RustBackups/wipescripts/./Fullwipe.sh  && sed -i 's/4244780/156066843/g' /home/alienatedmammal/lgsm/config-lgsm/rustserver/common.cfg ; sed -i 's/4244780/156066843/g' /home/alienatedmammal/lgsm/config-lgsm/rustserver/rustserver.cfg ; sed -i 's/1\/4\/24/1\/18\/24/g' /home/alienatedmammal/lgsm/config-lgsm/rustserver/common.cfg ; sed -i 's/1\/4\/24/1\/18\/24/g' /home/alienatedmammal/lgsm/config-lgsm/rustserver/rustserver.cfg ; sed -i 's/1\/4\/24/1\/18\/24/g' /home/alienatedmammal/serverfiles/oxide/config/ServerInfo.json ; sed -i 's/1\/4\/24/1\/18\/24/g' /home/alienatedmammal/serverfiles/oxide/config/SmartChatBot.json ; echo Files have been copied >> /home/alienatedmammal/Documents/RustBackups/wipescripts/Logs/Logs.txt || echo Failed to copy files >> /home/alienatedmammal/Documents/RustBackups/wipescripts/Logs/Logs.txt && echo Server is now starting.... >> /home/alienatedmammal/Documents/RustBackups/wipescripts/Logs/Logs.txt ; /home/alienatedmammal/Documents/RustBackups/wipescripts/./ServerStart.sh"
commands["2024-01-18"]="/home/alienatedmammal/Documents/RustBackups/wipescripts/./Mapwipe.sh && sed -i 's/1\/18\/24/2\/1\/24/g' /home/alienatedmammal/lgsm/config-lgsm/rustserver/common.cfg ; sed -i 's/1\/18\/24/2\/1\/24/g' /home/alienatedmammal/lgsm/config-lgsm/rustserver/rustserver.cfg ; sed -i 's/1\/18\/24/2\/1\/24/g' /home/alienatedmammal/serverfiles/oxide/config/ServerInfo.json ; sed -i 's/1\/18\/24/2\/1\/24/g' /home/alienatedmammal/serverfiles/oxide/config/SmartChatBot.json ; echo Files have been copied >> /home/alienatedmammal/Documents/RustBackups/wipescripts/Logs/Logs.txt || echo Failed to copy files >> /home/alienatedmammal/Documents/RustBackups/wipescripts/Logs/Logs.txt && echo Server is now starting.... >> /home/alienatedmammal/Documents/RustBackups/wipescripts/Logs/Logs.txt ; /home/alienatedmammal/Documents/RustBackups/wipescripts/./ServerStart.sh"
commands["2024-02-01"]="/home/alienatedmammal/Documents/RustBackups/wipescripts/./Fullwipe.sh && sed -i 's/156066843/1984572167/g' /home/alienatedmammal/lgsm/config-lgsm/rustserver/common.cfg ; sed -i 's/156066843/1984572167/g' /home/alienatedmammal/lgsm/config-lgsm/rustserver/rustserver.cfg ; sed -i 's/2\/1\/24/2\/15\/24/g' /home/alienatedmammal/lgsm/config-lgsm/rustserver/common.cfg ; sed -i 's/2\/1\/24/2\/15\/24/g' /home/alienatedmammal/lgsm/config-lgsm/rustserver/rustserver.cfg ; sed -i 's/2\/1\/24/2\/15\/24/g' /home/alienatedmammal/serverfiles/oxide/config/ServerInfo.json ; sed -i 's/2\/1\/24/2\/15\/24/g' /home/alienatedmammal/serverfiles/oxide/config/SmartChatBot.json ; echo Files have been copied >> /home/alienatedmammal/Documents/RustBackups/wipescripts/Logs/Logs.txt || echo Failed to copy files >> /home/alienatedmammal/Documents/RustBackups/wipescripts/Logs/Logs.txt && echo Server is now starting.... >> /home/alienatedmammal/Documents/RustBackups/wipescripts/Logs/Logs.txt ; /home/alienatedmammal/Documents/RustBackups/wipescripts/./ServerStart.sh"
commands["2024-02-15"]="/home/alienatedmammal/Documents/RustBackups/wipescripts/./Mapwipe.sh && sed -i 's/2\/15\/24/2\/29\/24/g' /home/alienatedmammal/lgsm/config-lgsm/rustserver/common.cfg ; sed -i 's/2\/15\/24/2\/29\/24/g' /home/alienatedmammal/lgsm/config-lgsm/rustserver/rustserver.cfg ; sed -i 's/2\/15\/24/2\/29\/24/g' /home/alienatedmammal/serverfiles/oxide/config/ServerInfo.json ; sed -i 's/2\/15\/24/2\/29\/24/g' /home/alienatedmammal/serverfiles/oxide/config/SmartChatBot.json ; echo Files have been copied >> /home/alienatedmammal/Documents/RustBackups/wipescripts/Logs/Logs.txt || echo Failed to copy files >> /home/alienatedmammal/Documents/RustBackups/wipescripts/Logs/Logs.txt && echo Server is now starting.... >> /home/alienatedmammal/Documents/RustBackups/wipescripts/Logs/Logs.txt ; /home/alienatedmammal/Documents/RustBackups/wipescripts/./ServerStart.sh"
commands["2024-02-29"]="/home/alienatedmammal/Documents/RustBackups/wipescripts/./Mapwipe.sh && sed -i 's/2\/29\/24/3\/7\/24/g' /home/alienatedmammal/lgsm/config-lgsm/rustserver/common.cfg ; sed -i 's/2\/29\/24/3\/7\/24/g' /home/alienatedmammal/lgsm/config-lgsm/rustserver/rustserver.cfg ; sed -i 's/2\/29\/24/3\/7\/24/g' /home/alienatedmammal/serverfiles/oxide/config/ServerInfo.json ; sed -i 's/2\/29\/24/3\/7\/24/g' /home/alienatedmammal/serverfiles/oxide/config/SmartChatBot.json ; echo Files have been copied >> /home/alienatedmammal/Documents/RustBackups/wipescripts/Logs/Logs.txt || echo Failed to copy files >> /home/alienatedmammal/Documents/RustBackups/wipescripts/Logs/Logs.txt && echo Server is now starting.... >> /home/alienatedmammal/Documents/RustBackups/wipescripts/Logs/Logs.txt ; /home/alienatedmammal/Documents/RustBackups/wipescripts/./ServerStart.sh"
commands["2024-03-07"]="/home/alienatedmammal/Documents/RustBackups/wipescripts/./Fullwipe.sh && sed -i 's/1984572167/250192951/g' /home/alienatedmammal/lgsm/config-lgsm/rustserver/common.cfg ; sed -i 's/1984572167/250192951/g' /home/alienatedmammal/lgsm/config-lgsm/rustserver/rustserver.cfg ; sed -i 's/3\/7\/24/3\/21\/24/g' /home/alienatedmammal/lgsm/config-lgsm/rustserver/common.cfg ; sed -i 's/3\/7\/24/3\/21\/24/g' /home/alienatedmammal/lgsm/config-lgsm/rustserver/rustserver.cfg ; sed -i 's/3\/7\/24/3\/21\/24/g' /home/alienatedmammal/serverfiles/oxide/config/ServerInfo.json ; sed -i 's/3\/7\/24/3\/21\/24/g' /home/alienatedmammal/serverfiles/oxide/config/SmartChatBot.json ; echo Files have been copied >> /home/alienatedmammal/Documents/RustBackups/wipescripts/Logs/Logs.txt || echo Failed to copy files >> /home/alienatedmammal/Documents/RustBackups/wipescripts/Logs/Logs.txt && echo Server is now starting.... >> /home/alienatedmammal/Documents/RustBackups/wipescripts/Logs/Logs.txt ; /home/alienatedmammal/Documents/RustBackups/wipescripts/./ServerStart.sh"
commands["2024-03-21"]="/home/alienatedmammal/Documents/RustBackups/wipescripts/./Mapwipe.sh && sed -i 's/3\/21\/24/4\/4\/24/g' /home/alienatedmammal/lgsm/config-lgsm/rustserver/common.cfg ; sed -i 's/3\/21\/24/4\/4\/24/g' /home/alienatedmammal/lgsm/config-lgsm/rustserver/rustserver.cfg ; sed -i 's/3\/21\/24/4\/4\/24/g' /home/alienatedmammal/serverfiles/oxide/config/ServerInfo.json ; sed -i 's/3\/21\/24/4\/4\/24/g' /home/alienatedmammal/serverfiles/oxide/config/SmartChatBot.json ; echo Files have been copied >> /home/alienatedmammal/Documents/RustBackups/wipescripts/Logs/Logs.txt || echo Failed to copy files >> /home/alienatedmammal/Documents/RustBackups/wipescripts/Logs/Logs.txt && echo Server is now starting.... >> /home/alienatedmammal/Documents/RustBackups/wipescripts/Logs/Logs.txt ; /home/alienatedmammal/Documents/RustBackups/wipescripts/./ServerStart.sh"
commands["2024-04-04"]="/home/alienatedmammal/Documents/RustBackups/wipescripts/./Fullwipe.sh  && sed -i 's/250192951/1318565295/g' /home/alienatedmammal/lgsm/config-lgsm/rustserver/common.cfg ; sed -i 's/250192951/1318565295/g' /home/alienatedmammal/lgsm/config-lgsm/rustserver/rustserver.cfg ; sed -i 's/4\/4\/24/4\/18\/24/g' /home/alienatedmammal/lgsm/config-lgsm/rustserver/common.cfg ; sed -i 's/4\/4\/24/4\/18\/24/g' /home/alienatedmammal/lgsm/config-lgsm/rustserver/rustserver.cfg ; sed -i 's/4\/4\/24/4\/18\/24/g' /home/alienatedmammal/serverfiles/oxide/config/ServerInfo.json ; sed -i 's/4\/4\/24/4\/18\/24/g' /home/alienatedmammal/serverfiles/oxide/config/SmartChatBot.json ; echo Files have been copied >> /home/alienatedmammal/Documents/RustBackups/wipescripts/Logs/Logs.txt || echo Failed to copy files >> /home/alienatedmammal/Documents/RustBackups/wipescripts/Logs/Logs.txt && echo Server is now starting.... >> /home/alienatedmammal/Documents/RustBackups/wipescripts/Logs/Logs.txt ; /home/alienatedmammal/Documents/RustBackups/wipescripts/./ServerStart.sh"
commands["2024-04-18"]="/home/alienatedmammal/Documents/RustBackups/wipescripts/./Mapwipe.sh && sed -i 's/4\/18\/24/5\/2\/24/g' /home/alienatedmammal/lgsm/config-lgsm/rustserver/common.cfg ; sed -i 's/4\/18\/24/5\/2\/24/g' /home/alienatedmammal/lgsm/config-lgsm/rustserver/rustserver.cfg ; sed -i 's/4\/18\/24/5\/2\/24/g' /home/alienatedmammal/serverfiles/oxide/config/ServerInfo.json ; sed -i 's/4\/18\/24/5\/2\/24/g' /home/alienatedmammal/serverfiles/oxide/config/SmartChatBot.json ; echo Files have been copied >> /home/alienatedmammal/Documents/RustBackups/wipescripts/Logs/Logs.txt || echo Failed to copy files >> /home/alienatedmammal/Documents/RustBackups/wipescripts/Logs/Logs.txt && echo Server is now starting.... >> /home/alienatedmammal/Documents/RustBackups/wipescripts/Logs/Logs.txt ; /home/alienatedmammal/Documents/RustBackups/wipescripts/./ServerStart.sh"
commands["2024-05-02"]="/home/alienatedmammal/Documents/RustBackups/wipescripts/./Fullwipe.sh && sed -i 's/1318565295/554247934/g' /home/alienatedmammal/lgsm/config-lgsm/rustserver/common.cfg ; sed -i 's/1318565295/554247934/g' /home/alienatedmammal/lgsm/config-lgsm/rustserver/rustserver.cfg ; sed -i 's/5\/2\/24/5\/16\/24/g' /home/alienatedmammal/lgsm/config-lgsm/rustserver/common.cfg ; sed -i 's/5\/2\/24/5\/16\/24/g' /home/alienatedmammal/lgsm/config-lgsm/rustserver/rustserver.cfg ; sed -i 's/5\/2\/24/5\/16\/24/g' /home/alienatedmammal/serverfiles/oxide/config/ServerInfo.json ; sed -i 's/5\/2\/24/5\/16\/24/g' /home/alienatedmammal/serverfiles/oxide/config/SmartChatBot.json ; echo Files have been copied >> /home/alienatedmammal/Documents/RustBackups/wipescripts/Logs/Logs.txt || echo Failed to copy files >> /home/alienatedmammal/Documents/RustBackups/wipescripts/Logs/Logs.txt && echo Server is now starting.... >> /home/alienatedmammal/Documents/RustBackups/wipescripts/Logs/Logs.txt ; /home/alienatedmammal/Documents/RustBackups/wipescripts/./ServerStart.sh"
commands["2024-05-16"]="/home/alienatedmammal/Documents/RustBackups/wipescripts/./Mapwipe.sh && sed -i 's/5\/16\/24/5\/30\/24/g' /home/alienatedmammal/lgsm/config-lgsm/rustserver/common.cfg ; sed -i 's/5\/16\/24/5\/30\/24/g' /home/alienatedmammal/lgsm/config-lgsm/rustserver/rustserver.cfg ; sed -i 's/5\/16\/24/5\/30\/24/g' /home/alienatedmammal/serverfiles/oxide/config/ServerInfo.json ; sed -i 's/5\/16\/24/5\/30\/24/g' /home/alienatedmammal/serverfiles/oxide/config/SmartChatBot.json ; echo Files have been copied >> /home/alienatedmammal/Documents/RustBackups/wipescripts/Logs/Logs.txt || echo Failed to copy files >> /home/alienatedmammal/Documents/RustBackups/wipescripts/Logs/Logs.txt && echo Server is now starting.... >> /home/alienatedmammal/Documents/RustBackups/wipescripts/Logs/Logs.txt ; /home/alienatedmammal/Documents/RustBackups/wipescripts/./ServerStart.sh"
commands["2024-05-30"]="/home/alienatedmammal/Documents/RustBackups/wipescripts/./Mapwipe.sh && sed -i 's/5\/30\/24/6\/6\/24/g' /home/alienatedmammal/lgsm/config-lgsm/rustserver/common.cfg ; sed -i 's/5\/30\/24/6\/6\/24/g' /home/alienatedmammal/lgsm/config-lgsm/rustserver/rustserver.cfg ; sed -i 's/5\/30\/24/6\/6\/24/g' /home/alienatedmammal/serverfiles/oxide/config/ServerInfo.json ; sed -i 's/5\/30\/24/6\/6\/24/g' /home/alienatedmammal/serverfiles/oxide/config/SmartChatBot.json ; echo Files have been copied >> /home/alienatedmammal/Documents/RustBackups/wipescripts/Logs/Logs.txt || echo Failed to copy files >> /home/alienatedmammal/Documents/RustBackups/wipescripts/Logs/Logs.txt && echo Server is now starting.... >> /home/alienatedmammal/Documents/RustBackups/wipescripts/Logs/Logs.txt ; /home/alienatedmammal/Documents/RustBackups/wipescripts/./ServerStart.sh"
commands["2024-06-06"]="/home/alienatedmammal/Documents/RustBackups/wipescripts/./Fullwipe.sh && sed -i 's/554247934/2147483435/g' /home/alienatedmammal/lgsm/config-lgsm/rustserver/common.cfg ; sed -i 's/554247934/2147483435/g' /home/alienatedmammal/lgsm/config-lgsm/rustserver/rustserver.cfg ; sed -i 's/6\/6\/24/6\/20\/24/g' /home/alienatedmammal/lgsm/config-lgsm/rustserver/common.cfg ; sed -i 's/6\/6\/24/6\/20\/24/g' /home/alienatedmammal/lgsm/config-lgsm/rustserver/rustserver.cfg ; sed -i 's/6\/6\/24/6\/20\/24/g' /home/alienatedmammal/serverfiles/oxide/config/ServerInfo.json ; sed -i 's/6\/6\/24/6\/20\/24/g' /home/alienatedmammal/serverfiles/oxide/config/SmartChatBot.json ; echo Files have been copied >> /home/alienatedmammal/Documents/RustBackups/wipescripts/Logs/Logs.txt || echo Failed to copy files >> /home/alienatedmammal/Documents/RustBackups/wipescripts/Logs/Logs.txt && echo Server is now starting.... >> /home/alienatedmammal/Documents/RustBackups/wipescripts/Logs/Logs.txt ; /home/alienatedmammal/Documents/RustBackups/wipescripts/./ServerStart.sh"
commands["2024-06-20"]="/home/alienatedmammal/Documents/RustBackups/wipescripts/./Mapwipe.sh && sed -i 's/6\/20\/24/7\/4\/24/g' /home/alienatedmammal/lgsm/config-lgsm/rustserver/common.cfg ; sed -i 's/6\/20\/24/7\/4\/24/g' /home/alienatedmammal/lgsm/config-lgsm/rustserver/rustserver.cfg ; sed -i 's/6\/20\/24/7\/4\/24/g' /home/alienatedmammal/serverfiles/oxide/config/ServerInfo.json ; sed -i 's/6\/20\/24/7\/4\/24/g' /home/alienatedmammal/serverfiles/oxide/config/SmartChatBot.json ; echo Files have been copied >> /home/alienatedmammal/Documents/RustBackups/wipescripts/Logs/Logs.txt || echo Failed to copy files >> /home/alienatedmammal/Documents/RustBackups/wipescripts/Logs/Logs.txt && echo Server is now starting.... >> /home/alienatedmammal/Documents/RustBackups/wipescripts/Logs/Logs.txt ; /home/alienatedmammal/Documents/RustBackups/wipescripts/./ServerStart.sh"
commands["2024-07-04"]="/home/alienatedmammal/Documents/RustBackups/wipescripts/./Fullwipe.sh && sed -i 's/2147483435/625143089/g' /home/alienatedmammal/lgsm/config-lgsm/rustserver/common.cfg ; sed -i 's/2147483435/625143089/g' /home/alienatedmammal/lgsm/config-lgsm/rustserver/rustserver.cfg ; sed -i 's/7\/4\/24/7\/18\/24/g' /home/alienatedmammal/lgsm/config-lgsm/rustserver/common.cfg ; sed -i 's/7\/4\/24/7\/18\/24/g' /home/alienatedmammal/lgsm/config-lgsm/rustserver/rustserver.cfg ; sed -i 's/7\/4\/24/7\/18\/24/g' /home/alienatedmammal/serverfiles/oxide/config/ServerInfo.json ; sed -i 's/7\/4\/24/7\/18\/24/g' /home/alienatedmammal/serverfiles/oxide/config/SmartChatBot.json ; echo Files have been copied >> /home/alienatedmammal/Documents/RustBackups/wipescripts/Logs/Logs.txt || echo Failed to copy files >> /home/alienatedmammal/Documents/RustBackups/wipescripts/Logs/Logs.txt && echo Server is now starting.... >> /home/alienatedmammal/Documents/RustBackups/wipescripts/Logs/Logs.txt ; /home/alienatedmammal/Documents/RustBackups/wipescripts/./ServerStart.sh"
commands["2024-07-18"]="/home/alienatedmammal/Documents/RustBackups/wipescripts/./Mapwipe.sh && sed -i 's/7\/18\/24/8\/1\/24/g' /home/alienatedmammal/lgsm/config-lgsm/rustserver/common.cfg ; sed -i 's/7\/18\/24/8\/1\/24/g' /home/alienatedmammal/lgsm/config-lgsm/rustserver/rustserver.cfg ; sed -i 's/7\/18\/24/8\/1\/24/g' /home/alienatedmammal/serverfiles/oxide/config/ServerInfo.json ; sed -i 's/7\/18\/24/8\/1\/24/g' /home/alienatedmammal/serverfiles/oxide/config/SmartChatBot.json ; echo Files have been copied >> /home/alienatedmammal/Documents/RustBackups/wipescripts/Logs/Logs.txt || echo Failed to copy files >> /home/alienatedmammal/Documents/RustBackups/wipescripts/Logs/Logs.txt && echo Server is now starting.... >> /home/alienatedmammal/Documents/RustBackups/wipescripts/Logs/Logs.txt ; /home/alienatedmammal/Documents/RustBackups/wipescripts/./ServerStart.sh"
commands["2024-08-01"]="/home/alienatedmammal/Documents/RustBackups/wipescripts/./Fullwipe.sh && sed -i 's/625143089/1030141252 /g' /home/alienatedmammal/lgsm/config-lgsm/rustserver/common.cfg ; sed -i 's/625143089/1030141252 /g' /home/alienatedmammal/lgsm/config-lgsm/rustserver/rustserver.cfg ; sed -i 's/8\/1\/24/8\/15\/24/g' /home/alienatedmammal/lgsm/config-lgsm/rustserver/common.cfg ; sed -i 's/8\/1\/24/8\/15\/24/g' /home/alienatedmammal/lgsm/config-lgsm/rustserver/rustserver.cfg ; sed -i 's/8\/1\/24/8\/15\/24/g' /home/alienatedmammal/serverfiles/oxide/config/ServerInfo.json ; sed -i 's/8\/1\/24/8\/15\/24/g' /home/alienatedmammal/serverfiles/oxide/config/SmartChatBot.json ; echo Files have been copied >> /home/alienatedmammal/Documents/RustBackups/wipescripts/Logs/Logs.txt || echo Failed to copy files >> /home/alienatedmammal/Documents/RustBackups/wipescripts/Logs/Logs.txt && echo Server is now starting.... >> /home/alienatedmammal/Documents/RustBackups/wipescripts/Logs/Logs.txt ; /home/alienatedmammal/Documents/RustBackups/wipescripts/./ServerStart.sh"
commands["2024-08-15"]="/home/alienatedmammal/Documents/RustBackups/wipescripts/./Mapwipe.sh && sed -i 's/8\/15\/24/8\/29\/24/g' /home/alienatedmammal/lgsm/config-lgsm/rustserver/common.cfg ; sed -i 's/8\/15\/24/8\/29\/24/g' /home/alienatedmammal/lgsm/config-lgsm/rustserver/rustserver.cfg ; sed -i 's/8\/15\/24/8\/29\/24/g' /home/alienatedmammal/serverfiles/oxide/config/ServerInfo.json ; sed -i 's/8\/15\/24/8\/29\/24/g' /home/alienatedmammal/serverfiles/oxide/config/SmartChatBot.json ; echo Files have been copied >> /home/alienatedmammal/Documents/RustBackups/wipescripts/Logs/Logs.txt || echo Failed to copy files >> /home/alienatedmammal/Documents/RustBackups/wipescripts/Logs/Logs.txt && echo Server is now starting.... >> /home/alienatedmammal/Documents/RustBackups/wipescripts/Logs/Logs.txt ; /home/alienatedmammal/Documents/RustBackups/wipescripts/./ServerStart.sh"
commands["2024-08-29"]="/home/alienatedmammal/Documents/RustBackups/wipescripts/./Mapwipe.sh && sed -i 's/8\/29\/24/9\/5\/24/g' /home/alienatedmammal/lgsm/config-lgsm/rustserver/common.cfg ; sed -i 's/8\/29\/24/9\/5\/24/g' /home/alienatedmammal/lgsm/config-lgsm/rustserver/rustserver.cfg ; sed -i 's/8\/29\/24/9\/5\/24/g' /home/alienatedmammal/serverfiles/oxide/config/ServerInfo.json ; sed -i 's/8\/29\/24/9\/5\/24/g' /home/alienatedmammal/serverfiles/oxide/config/SmartChatBot.json ; echo Files have been copied >> /home/alienatedmammal/Documents/RustBackups/wipescripts/Logs/Logs.txt || echo Failed to copy files >> /home/alienatedmammal/Documents/RustBackups/wipescripts/Logs/Logs.txt && echo Server is now starting.... >> /home/alienatedmammal/Documents/RustBackups/wipescripts/Logs/Logs.txt ; /home/alienatedmammal/Documents/RustBackups/wipescripts/./ServerStart.sh"
commands["2024-09-05"]="/home/alienatedmammal/Documents/RustBackups/wipescripts/./Fullwipe.sh && sed -i 's/1030141252/456002067/g' /home/alienatedmammal/lgsm/config-lgsm/rustserver/common.cfg ; sed -i 's/1030141252/456002067/g' /home/alienatedmammal/lgsm/config-lgsm/rustserver/rustserver.cfg ; sed -i 's/9\/5\/24/9\/19\/24/g' /home/alienatedmammal/lgsm/config-lgsm/rustserver/common.cfg ; sed -i 's/9\/5\/24/9\/19\/24/g' /home/alienatedmammal/lgsm/config-lgsm/rustserver/rustserver.cfg ; sed -i 's/9\/5\/24/9\/19\/24/g' /home/alienatedmammal/serverfiles/oxide/config/ServerInfo.json ; sed -i 's/9\/5\/24/9\/19\/24/g' /home/alienatedmammal/serverfiles/oxide/config/SmartChatBot.json ; echo Files have been copied >> /home/alienatedmammal/Documents/RustBackups/wipescripts/Logs/Logs.txt || echo Failed to copy files >> /home/alienatedmammal/Documents/RustBackups/wipescripts/Logs/Logs.txt && echo Server is now starting.... >> /home/alienatedmammal/Documents/RustBackups/wipescripts/Logs/Logs.txt ; /home/alienatedmammal/Documents/RustBackups/wipescripts/./ServerStart.sh"
commands["2024-09-19"]="/home/alienatedmammal/Documents/RustBackups/wipescripts/./Mapwipe.sh && sed -i 's/9\/19\/24/10\/3\/24/g' /home/alienatedmammal/lgsm/config-lgsm/rustserver/common.cfg ; sed -i 's/9\/19\/24/10\/3\/24/g' /home/alienatedmammal/lgsm/config-lgsm/rustserver/rustserver.cfg ; sed -i 's/9\/19\/24/10\/3\/24/g' /home/alienatedmammal/serverfiles/oxide/config/ServerInfo.json ; sed -i 's/9\/19\/24/10\/3\/24/g' /home/alienatedmammal/serverfiles/oxide/config/SmartChatBot.json ; echo Files have been copied >> /home/alienatedmammal/Documents/RustBackups/wipescripts/Logs/Logs.txt || echo Failed to copy files >> /home/alienatedmammal/Documents/RustBackups/wipescripts/Logs/Logs.txt && echo Server is now starting.... >> /home/alienatedmammal/Documents/RustBackups/wipescripts/Logs/Logs.txt ; /home/alienatedmammal/Documents/RustBackups/wipescripts/./ServerStart.sh"
commands["2024-10-03"]="/home/alienatedmammal/Documents/RustBackups/wipescripts/./Fullwipe.sh && sed -i 's/456002067/1813703292/g' /home/alienatedmammal/lgsm/config-lgsm/rustserver/common.cfg ; sed -i 's/456002067/1813703292/g' /home/alienatedmammal/lgsm/config-lgsm/rustserver/rustserver.cfg ; sed -i 's/10\/3\/24/10\/17\/24/g' /home/alienatedmammal/lgsm/config-lgsm/rustserver/common.cfg ; sed -i 's/10\/3\/24/10\/17\/24/g' /home/alienatedmammal/lgsm/config-lgsm/rustserver/rustserver.cfg ; sed -i 's/10\/3\/24/10\/17\/24/g' /home/alienatedmammal/serverfiles/oxide/config/ServerInfo.json ; sed -i 's/10\/3\/24/10\/17\/24/g' /home/alienatedmammal/serverfiles/oxide/config/SmartChatBot.json ; echo Files have been copied >> /home/alienatedmammal/Documents/RustBackups/wipescripts/Logs/Logs.txt || echo Failed to copy files >> /home/alienatedmammal/Documents/RustBackups/wipescripts/Logs/Logs.txt && echo Server is now starting.... >> /home/alienatedmammal/Documents/RustBackups/wipescripts/Logs/Logs.txt ; /home/alienatedmammal/Documents/RustBackups/wipescripts/./ServerStart.sh"
commands["2024-10-17"]="/home/alienatedmammal/Documents/RustBackups/wipescripts/./Mapwipe.sh && sed -i 's/10\/17\/24/10\/31\/24/g' /home/alienatedmammal/lgsm/config-lgsm/rustserver/common.cfg ; sed -i 's/10\/17\/24/10\/31\/24/g' /home/alienatedmammal/lgsm/config-lgsm/rustserver/rustserver.cfg ; sed -i 's/10\/17\/24/10\/31\/24/g' /home/alienatedmammal/serverfiles/oxide/config/ServerInfo.json ; sed -i 's/10\/17\/24/10\/31\/24/g' /home/alienatedmammal/serverfiles/oxide/config/SmartChatBot.json ; echo Files have been copied >> /home/alienatedmammal/Documents/RustBackups/wipescripts/Logs/Logs.txt || echo Failed to copy files >> /home/alienatedmammal/Documents/RustBackups/wipescripts/Logs/Logs.txt && echo Server is now starting.... >> /home/alienatedmammal/Documents/RustBackups/wipescripts/Logs/Logs.txt ; /home/alienatedmammal/Documents/RustBackups/wipescripts/./ServerStart.sh"
commands["2024-10-31"]="/home/alienatedmammal/Documents/RustBackups/wipescripts/./Mapwipe.sh && sed -i 's/10\/31\/24/11\/7\/24/g' /home/alienatedmammal/lgsm/config-lgsm/rustserver/common.cfg ; sed -i 's/10\/31\/24/11\/7\/24/g' /home/alienatedmammal/lgsm/config-lgsm/rustserver/rustserver.cfg ; sed -i 's/10\/31\/24/11\/7\/24/g' /home/alienatedmammal/serverfiles/oxide/config/ServerInfo.json ; sed -i 's/10\/31\/24/11\/7\/24/g' /home/alienatedmammal/serverfiles/oxide/config/SmartChatBot.json ; echo Files have been copied >> /home/alienatedmammal/Documents/RustBackups/wipescripts/Logs/Logs.txt || echo Failed to copy files >> /home/alienatedmammal/Documents/RustBackups/wipescripts/Logs/Logs.txt && echo Server is now starting.... >> /home/alienatedmammal/Documents/RustBackups/wipescripts/Logs/Logs.txt ;  /home/alienatedmammal/Documents/RustBackups/wipescripts/./ServerStart.sh"
commands["2024-11-07"]="/home/alienatedmammal/Documents/RustBackups/wipescripts/./Fullwipe.sh && sed -i 's/1813703292/682113486/g' /home/alienatedmammal/lgsm/config-lgsm/rustserver/common.cfg ; sed -i 's/1813703292/682113486/g' /home/alienatedmammal/lgsm/config-lgsm/rustserver/rustserver.cfg ; sed -i 's/11\/7\/24/11\/21\/24/g' /home/alienatedmammal/lgsm/config-lgsm/rustserver/common.cfg ; sed -i 's/11\/7\/24/11\/21\/24/g' /home/alienatedmammal/lgsm/config-lgsm/rustserver/rustserver.cfg ; sed -i 's/11\/7\/24/11\/21\/24/g' /home/alienatedmammal/serverfiles/oxide/config/ServerInfo.json ; sed -i 's/11\/7\/24/11\/21\/24/g' /home/alienatedmammal/serverfiles/oxide/config/SmartChatBot.json ; echo Files have been copied >> /home/alienatedmammal/Documents/RustBackups/wipescripts/Logs/Logs.txt || echo Failed to copy files >> /home/alienatedmammal/Documents/RustBackups/wipescripts/Logs/Logs.txt && echo Server is now starting.... >> /home/alienatedmammal/Documents/RustBackups/wipescripts/Logs/Logs.txt ; /home/alienatedmammal/Documents/RustBackups/wipescripts/./ServerStart.sh"
commands["2024-11-21"]="/home/alienatedmammal/Documents/RustBackups/wipescripts/./Mapwipe.sh && sed -i 's/11\/21\/24/11\/28\/24/g' /home/alienatedmammal/lgsm/config-lgsm/rustserver/common.cfg ; sed -i 's/11\/21\/24/11\/28\/24/g' /home/alienatedmammal/lgsm/config-lgsm/rustserver/rustserver.cfg ; sed -i 's/11\/21\/24/11\/28\/24/g' /home/alienatedmammal/serverfiles/oxide/config/ServerInfo.json ; sed -i 's/11\/21\/24/11\/28\/24/g' /home/alienatedmammal/serverfiles/oxide/config/SmartChatBot.json ; echo Files have been copied >> /home/alienatedmammal/Documents/RustBackups/wipescripts/Logs/Logs.txt || echo Failed to copy files >> /home/alienatedmammal/Documents/RustBackups/wipescripts/Logs/Logs.txt && echo Server is now starting.... >> /home/alienatedmammal/Documents/RustBackups/wipescripts/Logs/Logs.txt ; /home/alienatedmammal/Documents/RustBackups/wipescripts/./ServerStart.sh"
commands["2024-11-28"]="/home/alienatedmammal/Documents/RustBackups/wipescripts/./Mapwipe.sh && sed -i 's/11\/28\/24/12\/5\/24/g' /home/alienatedmammal/lgsm/config-lgsm/rustserver/common.cfg ; sed -i 's/11\/28\/24/12\/5\/24/g' /home/alienatedmammal/lgsm/config-lgsm/rustserver/rustserver.cfg ; sed -i 's/11\/28\/24/12\/5\/24/g' /home/alienatedmammal/serverfiles/oxide/config/ServerInfo.json ; sed -i 's/11\/28\/24/12\/5\/24/g' /home/alienatedmammal/serverfiles/oxide/config/SmartChatBot.json ; echo Files have been copied >> /home/alienatedmammal/Documents/RustBackups/wipescripts/Logs/Logs.txt || echo Failed to copy files >> /home/alienatedmammal/Documents/RustBackups/wipescripts/Logs/Logs.txt && echo Server is now starting.... >> /home/alienatedmammal/Documents/RustBackups/wipescripts/Logs/Logs.txt ; /home/alienatedmammal/Documents/RustBackups/wipescripts/./ServerStart.sh"





# Check if the current date matches any of the target dates
for target_date in "${!commands[@]}"; do
    if [ "$current_date" == "$target_date" ]; then
        # Run the corresponding command for the matched date
        echo "Today's date matches a target date ($target_date). Running the command..." >> $LOGS
        eval "${commands[$target_date]}"
        exit 0
    fi
done

# If no matches 
echo "$(date)" "There is no wipe this week." >> $LOGS

